export enum NotificationSubscriptionTopic {
  ADMINS = 'ADMINS',
  THERAPISTS = 'THERAPISTS',
  PATIENTS = 'PATIENTS',
  PROMOTIONS = 'PROMOTIONS',
  ANNOUNCEMENTS = 'ANNOUNCEMENTS',
  OTHER = 'OTHER',
}
