export const DEFAULT_PAGE_SIZE = 100;
export const DEFAULT_SALT_ROUNDS = 10;
export const SESSION_USER_KEY = 'SESSION_USER';
export const DATABASE_ERROR_MESSAGES = {
  UNIQUE_VIOLATION: (column: string) => `This ${column} already exists`,
  CONFLICT_VIOLATION: `This resource conflicts with another resource`,
  NOT_NULL_VIOLATION: (column: string) => `${column} cannot be null`,
  FOREIGN_KEY_VIOLATION: 'Invalid reference to another entity',
  CHECK_VIOLATION: 'Invalid data violates business rules',
  STRING_DATA_RIGHT_TRUNCATION: 'Data too long for field',
  NUMERIC_VALUE_OUT_OF_RANGE: 'Numeric value out of range',
  INVALID_TEXT_REPRESENTATION: 'Invalid data format',
  INVALID_DATETIME_FORMAT: 'Invalid date/time format',
  DEADLOCK_DETECTED: 'Database deadlock occurred',
  INSUFFICIENT_PRIVILEGE: 'Insufficient database privileges',
  DUPLICATE_COLUMN: 'Duplicate column name',
  UNDEFINED_COLUMN: 'Column does not exist',
  UNDEFINED_TABLE: 'Table does not exist',
  SYNTAX_ERROR: 'Database syntax error',
  CONNECTION_ERROR: 'Database connection error',
  TIMEOUT_ERROR: 'Database operation timed out',
  DEFAULT_DATABASE_ERROR: 'Database operation failed',
  TRANSACTION_ERROR: 'Transaction error occurred',
  LOCK_NOT_AVAILABLE: 'Resource is locked by another transaction',
  OUT_OF_MEMORY: 'Database out of memory',
  DISK_FULL: 'Database disk is full',
  TOO_MANY_CONNECTIONS: 'Too many database connections',
  OBJECT_IN_USE: 'Database object is in use',
  ADMIN_SHUTDOWN: 'Database is shutting down',
  CRASH_SHUTDOWN: 'Database crashed',
  CANNOT_CONNECT_NOW: 'Cannot connect to database now',
  SERIALIZATION_FAILURE: 'Transaction serialization failure',
  READ_ONLY_SQL_TRANSACTION: 'Cannot write in read-only transaction',
  DEFAULT: 'An unexpected database error occurred',
};
